### ISSUE TITLE
The new_cop command started to fail after adding the support to Ruby 2.4

### ISSUE THREAD

**Issue by MassimilianoLattanzio** [solidusio/rubocop-solidus#46]
The `new_cop` command is not working anymore because of an issue with the `RuboCop::Cop::Generator` class in the Rakefile.

After adding the support to Ruby 2.4, we had to [downgrade rubocop version](https://github.com/nebulab/rubocop-solidus/blame/d52544527add8bb4a81970fbae964e022e055ab8/Gemfile.lock#L40). The old version of [`RuboCop::Cop::Generator`](https://github.com/rubocop/rubocop/blob/adf5629f5d2b22336185286c5197fdf6a4153382/lib/rubocop/cop/generator.rb#L109) class used an additional `github_user` parameter that is not present in [our Rakefile](https://github.com/nebulab/rubocop-solidus/blob/7b7e07b3b9d74f697a95f8bff7b25ee594c99cec/Rakefile#L26). So when you run the `new_cop` command results in this error:
```
ArgumentError: wrong number of arguments (given 1, expected 2)
rubocop-solidus/Rakefile:26:in `new'
```

After discussing with @abhishekgupta5 and @piyushswain, we thought the best way to solve this issue would be to create a separate branch with support for Ruby 2.4 but remove it from the main branch.

We could fix this issue in particular, but something else could not work properly because we used the latest version of the extension generator, but we are using an old version of rubocop, resulting in classes being misused.

@DanielePalombo, WDYT?

**Comment by DanielePalombo** [comment]
Yes, I think this could be a good solution.
