### ISSUE TITLE
Investigate how the rubocop warning are working

### ISSUE THREAD

**Issue by DanielePalombo** [solidusio/rubocop-solidus#49]
If possible support it and update the readme and documentation as well

**Comment by abhishekgupta5** [comment]
From the rubocop [docs](Severity

Severity

Each cop has a default severity level based on which department it belongs to. The level is normally warning for Lint and convention for all the others, but this can be changed in user configuration. Cops can customize their severity level. Allowed values are info, refactor, convention, warning, error and fatal.

Cops with severity info will be reported but will not cause rubocop to return a non-zero value.

There is one exception from the general rule above and that is Lint/Syntax, a special cop that checks for syntax errors before the other cops are invoked. It cannot be disabled and its severity (fatal) cannot be changed in configuration.

Lint:
  Severity: error

Metrics/CyclomaticComplexity:
  Severity: warning

**Comment by piyushswain** [comment]
@DanielePalombo @MassimilianoLattanzio @abhishekgupta5 
From the Rubocop Docs, Rubydoc.info and checking the source code
- https://www.rubydoc.info/gems/rubocop/RuboCop/RSpec/ExpectOffense
- https://github.com/rubocop/rubocop/blob/master/lib/rubocop/rspec/expect_offense.rb
- https://www.rubydoc.info/gems/rubocop/RuboCop%2FCop%2FBase:add_offense#:~:text=Adds%20an%20offense%20on%20the,'message%60%20will%20be%20called.

Hey guys,
I have found a way to set a severity on a cop offense and also to test this behaviour in the specs.

------
**Modifications required in a Cop**

Lets take this cop for example.
```rb
class ClassEvalDecorator < Base
  MSG = 'Do not use `class_eval` flag. Use a decorator module instead. Check this link for an example https://guides.solidus.io/cookbook/redefining-checkout-steps'

  RESTRICT_ON_SEND = %i[class_eval].freeze

  def_node_matcher :on_class_eval?, <<~PATTERN
    (send  ($...) :class_eval)
  PATTERN

  def on_send(node)
    return unless on_class_eval?(node)

    add_offense(node)
  end
end
```

Now if we want to modify this offense from a `error` to `warning` then we need to modify the following line
```rb
add_offense(node, severity: :warning)
```
The above line modifies the severity of the `RuboCop::Cop::Offense` object returned by the `add_offense` method.

Returned Object (For Error Level Offense)
```sh
[#<RuboCop::Cop::Offense:0x000000011e1de830
  @cop_name="Solidus/ClassEvalDecorator",
  @corrector=nil,
  @location=#<Parser::Source::Range (string) 0...18>,
  @message="Do not use `class_eval` flag. Use a decorator module instead. Check this link for an example https://guides.solidus.io/cookbook/redefining-checkout-steps",
  @severity=#<RuboCop::Cop::Severity:0x000000011e1de808 @name=:convention>]
```
Returned Object (For Warning Level Offense)
```sh
[#<RuboCop::Cop::Offense:0x000000011cda1250
  @cop_name="Solidus/ClassEvalDecorator",
  @corrector=nil,
  @location=#<Parser::Source::Range (string) 0...18>,
  @message="Do not use `class_eval` flag. Use a decorator module instead. Check this link for an example https://guides.solidus.io/cookbook/redefining-checkout-steps",
  @severity=#<RuboCop::Cop::Severity:0x000000011cda1228 @name=:warning>]
```
------
**Now, onto RSpec**
I checked the `expect_offense` method of rspec and it had an argument for severity of the offense as well.
So, we can test our offenses in the following way.

Older Tests
```rb
expect_offense(<<~RUBY)
      Product.class_eval do
      ^^^^^^^^^^^^^^^^^^ Do not use `class_eval` flag. Use a decorator module instead. Check this link for an example https://guides.solidus.io/cookbook/redefining-checkout-steps\n
      end
RUBY
```

New Tests with severity warning
```rb
expect_offense(<<~RUBY, severity: :warning)
      Product.class_eval do
      ^^^^^^^^^^^^^^^^^^ Do not use `class_eval` flag. Use a decorator module instead. Check this link for an example https://guides.solidus.io/cookbook/redefining-checkout-steps\n
      end

RUBY
```

When the severity level does not match in a test then we get the following error.
```sh
Failure/Error:
       expected: [:warning]
       got: [#<RuboCop::Cop::Severity:0x000000011e1de808 @name=:convention>]
```


One thing to keep in mind is the heirarchy of severity in rubocop
Rubocop has multiple severity levels for a cop
- [info refactor convention warning error fatal]

I have noticed that the `expect_offense` method works in a way where the higher severity will always catch an offense with a lower severity and pass it through.

- Example 1 - If my offense has a severity of `refactor` but the `expect_offense` method checks for `warning` severity then this example will pass.
- Example 2 - If my offense has a severity of `error` but the `expect_offense` method checks for `warning` severity then this example will cause a failure in the test

**Comment by MassimilianoLattanzio** [comment]
Thanks for the investigation @piyushswain! Do we need to modify some severities in our current cops?

**Comment by piyushswain** [comment]
@MassimilianoLattanzio I'm not sure, we should probably discuss which cops we would like to set a severity for in a donut probably or if you have some cops in mind we can start changing them.
